// Code generated by mockery (devel). DO NOT EDIT.

package handlerutil

import (
	context "context"

	events "github.com/aws/aws-lambda-go/events"

	mock "github.com/stretchr/testify/mock"
)

// APIGatewayLambdaHandler is an autogenerated mock type for the APIGatewayLambdaHandler type
type APIGatewayLambdaHandler struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, request
func (_m *APIGatewayLambdaHandler) Execute(ctx context.Context, request events.APIGatewayProxyRequest) (events.APIGatewayProxyResponse, error) {
	ret := _m.Called(ctx, request)

	var r0 events.APIGatewayProxyResponse
	if rf, ok := ret.Get(0).(func(context.Context, events.APIGatewayProxyRequest) events.APIGatewayProxyResponse); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(events.APIGatewayProxyResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, events.APIGatewayProxyRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
