// Code generated by mockery (devel). DO NOT EDIT.

package movie

import (
	movie "github.com/gkatanacio/sample-lambda-app/pkg/movie"
	mock "github.com/stretchr/testify/mock"
)

// ProcessMovieQueuer is an autogenerated mock type for the ProcessMovieQueuer type
type ProcessMovieQueuer struct {
	mock.Mock
}

// SendMovieForProcessing provides a mock function with given fields: _a0
func (_m *ProcessMovieQueuer) SendMovieForProcessing(_a0 movie.Movie) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(movie.Movie) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
